#!/usr/bin/env python3
"""Run the five handbook scenarios (plus the cross-platform stitch) against a fresh brain and
write one worked example per scenario, each with the audit entry it produced, to docs/scenarios/.

    python scripts/run_scenarios.py            # temp data dir, writes docs/scenarios/*.md
    python scripts/run_scenarios.py --print    # also print answers to the terminal

No LLM key is needed: the run uses the deterministic stub planner and extractive answerer,
so the audit entries below are reproducible. With LLM_API_KEY set, the same script exercises
the real models.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from fastapi.testclient import TestClient  # noqa: E402

from internal_brain.api.app import create_app  # noqa: E402
from internal_brain.config import Settings  # noqa: E402

DOCS = ROOT / "docs" / "scenarios"

Q1 = "What's the status of the database migration and were there blockers raised in Slack last week?"
Q2 = "What's the latest runbook for the payment-service incident?"
Q3 = "Where is the Q3 breach report?"
Q3_CONTROL = "Where is the Q9 llama report?"
Q_STITCH = "Root cause of the payment outage last quarter and the follow-up tickets"
STEP4 = "Step 4 (failover): promote the standby gateway in ap-southeast-1b and shift the DNS weight to 100% on the standby; roll back when the primary passes health checks."


class Runner:
    def __init__(self, client: TestClient, verbose: bool):
        self.c = client
        self.verbose = verbose
        self.brain = client.app.state.brain

    def ask(self, user: str, question: str):
        r = self.c.post("/ask", json={"question": question}, headers={"X-User-Id": user})
        r.raise_for_status()
        seq = int(r.headers["X-Audit-Seq"])
        entry = self.c.get(f"/audit/entries/{seq}", headers={"X-User-Id": "compliance"}).json()["entry"]
        if self.verbose:
            print(f"\n[{user}] {question}\n{r.json()['answer']}\n")
        return r.json(), seq, entry, r

    def admin(self, method: str, path: str, **kwargs):
        r = self.c.request(method, path, headers={"X-User-Id": "admin"}, **kwargs)
        r.raise_for_status()
        return r.json()

    def compliance(self, path: str, **params):
        r = self.c.get(path, params=params, headers={"X-User-Id": "compliance"})
        r.raise_for_status()
        return r.json()


def md_answer(user: str, question: str, body: dict, seq: int) -> str:
    lines = [f"**Asked as** `{user}` · **audit #{seq}**", "", f"> {question}", "", "**Answer**", "", body["answer"], ""]
    if body["citations"]:
        lines += ["**Citations**", ""]
        for c in body["citations"]:
            lines.append(f"- `{c['doc']}` — {c['title']} ({c['platform']}, updated {c['updated']})")
        lines += ["", "**Why the asker could see them (provenance)**", ""]
        for p in body["provenance"]:
            lines.append(f"- `{p['doc']}` granted by `{p['rule']}` (version {p['version']}, verified {p['verified_at']})")
    else:
        lines += ["_No citations: the uniform no-result response._"]
    return "\n".join(lines) + "\n"


def md_entry(entry: dict, title: str = "Audit entry") -> str:
    slim = dict(entry)
    return f"**{title}**\n\n```json\n{json.dumps(slim, indent=2, ensure_ascii=False)}\n```\n"


def md_decisions(entry: dict) -> str:
    rows = ["| Document | Gate 1 | Gate 2 | Rule | Version | Refreshed | Source |", "|---|---|---|---|---|---|---|"]
    for d in entry["decisions"]:
        rows.append(f"| `{d['doc']}` | {d['gate1']} | {d['gate2']} | `{d['rule']}` | {d['version']} | {'yes' if d['refreshed'] else ''} | {d['source']} |")
    return "\n".join(rows) + "\n"


def write(name: str, content: str) -> None:
    DOCS.mkdir(parents=True, exist_ok=True)
    (DOCS / name).write_text(content, encoding="utf-8")
    print(f"wrote docs/scenarios/{name}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--print", dest="verbose", action="store_true")
    parser.add_argument("--data-dir", default=None, help="use this data dir instead of a temp one (the audit chain there will be tampered at the end)")
    args = parser.parse_args()

    for var in ("VERIFIER",):
        os.environ.pop(var, None)
    data_dir = Path(args.data_dir) if args.data_dir else Path(tempfile.mkdtemp(prefix="brain-scenarios-"))
    settings = Settings(data_dir=data_dir, sync_interval_s=0, checkpoint_every=5)
    app = create_app(settings, initial_sync=True, poller=False)

    with TestClient(app) as client:
        run = Runner(client, args.verbose)
        mode = client.get("/health").json()
        header = f"_Generated by `scripts/run_scenarios.py` · planner: {mode['planner']} · answerer: {mode['answerer']} · embeddings: {mode['embeddings']}_\n\n"

        # ---------------- Scenario 1
        body1, seq1, entry1, _ = run.ask("jdoe", Q1)
        leads = [d for d in entry1["decisions"] if d["doc"].startswith("slack:C0DBML:")]
        write(
            "scenario-1-unified-query.md",
            "# Scenario 1 — Unified query\n\n" + header
            + "jdoe belongs to #db-migration and the DBM project but not to the private #db-migration-leads channel. "
            "The planner routes to Jira and Slack (and the other platforms with no time window); Gate 1 excludes the leads thread inside the index query; "
            "rank fusion merges the platforms; the answer cites DBM-42, DBM-45 and the #db-migration thread.\n\n"
            + md_answer("jdoe", Q1, body1, seq1)
            + "\n**Evidence on screen**: the audit entry shows the leads thread as `deny:not_member` — found by the query, never shown to the model.\n\n"
            + md_decisions(entry1) + "\n" + md_entry(entry1),
        )

        # ---------------- Scenario 3 (before any permission changes)
        body3, seq3, entry3, r3 = run.ask("ctr-lee", Q3)
        bodyc, seqc, entryc, rc = run.ask("ctr-lee", Q3_CONTROL)
        identical = r3.content == rc.content
        write(
            "scenario-3-negative-case.md",
            "# Scenario 3 — Negative case, no metadata side-channel\n\n" + header
            + "ctr-lee, an external contractor, holds no Confluence token at all, so Gate 1 never returns the Q3 breach report. "
            "The response is the uniform no-result message. The control query asks for a report that does not exist.\n\n"
            + "## The restricted document\n\n" + md_answer("ctr-lee", Q3, body3, seq3)
            + "\n## The control (non-existent document)\n\n" + md_answer("ctr-lee", Q3_CONTROL, bodyc, seqc)
            + f"\n**Byte-identical response bodies**: `{identical}` (audit sequence travels in the `X-Audit-Seq` header, not the body).\n\n"
            + "**Evidence on screen**: the two audit entries differ — `deny:not_member` on the report versus no candidate at all (`no_match`).\n\n"
            + "### Audit decisions, restricted document\n\n" + md_decisions(entry3)
            + "\n### Audit decisions, control\n\n" + (md_decisions(entryc) if entryc["decisions"] else "_No candidates: no_match._\n")
            + "\n" + md_entry(entry3, "Audit entry (restricted)") + "\n" + md_entry(entryc, "Audit entry (control)"),
        )

        # ---------------- Cross-platform stitch
        bodys, seqs, entrys, _ = run.ask("jdoe", Q_STITCH)
        write(
            "cross-platform-stitch.md",
            "# Cross-platform stitch — Drive postmortem to Jira tickets\n\n" + header
            + "The postmortem in the Engineering shared drive links PAY-231 and PAY-232. Link expansion follows the references one hop; "
            "each expanded ticket passes Gate 1 and Gate 2 on its own. PAY-260 (issue security level \"Security only\") never appears for jdoe.\n\n"
            + md_answer("jdoe", Q_STITCH, bodys, seqs) + "\n" + md_decisions(entrys) + "\n" + md_entry(entrys),
        )

        # ---------------- Scenario 4: live revocation (event delivered)
        before4, seqb4, entryb4, _ = run.ask("jdoe", Q1)
        thread = next(c["doc"] for c in before4["citations"] if c["doc"].startswith("slack:C0DBM:"))
        run.admin("POST", "/admin/slack/channels/C0DBM/members", json={"user_id": "jdoe", "member": False, "notify": True})
        after4, seqa4, entrya4, _ = run.ask("jdoe", Q1)
        # missed-webhook variant: add back, then remove without the event
        run.admin("POST", "/admin/slack/channels/C0DBM/members", json={"user_id": "jdoe", "member": True, "notify": True})
        run.ask("jdoe", Q1)
        run.admin("POST", "/admin/slack/channels/C0DBM/members", json={"user_id": "jdoe", "member": False, "notify": False})
        missed4, seqm4, entrym4, _ = run.ask("jdoe", Q1)
        run.admin("POST", "/admin/slack/channels/C0DBM/members", json={"user_id": "jdoe", "member": True, "notify": True})
        write(
            "scenario-4-live-revocation.md",
            "# Scenario 4 — Live revocation\n\n" + header
            + f"jdoe is removed from #db-migration (`C0DBM`). The membership event invalidates the entitlement cache, so the next query's Gate 1 filter "
            f"no longer carries `slack:channel:C0DBM` and the thread `{thread}` vanishes. The audit records `deny:revoked` because this user had received the document before.\n\n"
            + "## Before\n\n" + md_answer("jdoe", Q1, before4, seqb4)
            + "\n## After removal (event delivered)\n\n" + md_answer("jdoe", Q1, after4, seqa4) + "\n" + md_decisions(entrya4)
            + "\n## Missed-webhook variant (notify=false)\n\nThe entitlement cache is still warm, so Gate 1 still returns the thread; Gate 2 asks Slack live and drops it: `gate1: allow, gate2: deny, rule: revoked`.\n\n"
            + md_answer("jdoe", Q1, missed4, seqm4) + "\n" + md_decisions(entrym4)
            + "\n" + md_entry(entrya4, "Audit entry (event delivered)") + "\n" + md_entry(entrym4, "Audit entry (missed webhook)"),
        )

        # ---------------- Scenario 2: freshness with the poller paused
        run.admin("POST", "/admin/sync/pause")
        edit = run.admin("POST", "/admin/confluence/pages/8812/edit", json={"append": STEP4, "notify": True})
        body2, seq2, entry2, _ = run.ask("jdoe", Q2)
        run.admin("POST", "/admin/sync/resume")
        write(
            "scenario-2-freshness.md",
            "# Scenario 2 — Data freshness (read-through refresh)\n\n" + header
            + f"The poller is paused, then the runbook is edited (version {edit['version']}, index still at {edit['indexed_version']}). "
            "Gate 2 sees the newer version at the source, fetches and re-chunks it for this answer, and updates the index as a side effect.\n\n"
            + md_answer("jdoe", Q2, body2, seq2)
            + "\n**Evidence on screen**: `refreshed: true`, version 7 → 8 on the runbook's decision.\n\n" + md_decisions(entry2) + "\n" + md_entry(entry2),
        )

        # ---------------- Scenario 5: audit inquiry + verify + tamper
        view = run.compliance("/audit/views/user-access", actor="jdoe", container="confluence:space:PAYGW", days=30)
        nl = run.compliance("/audit/nl", q="Everything jdoe accessed related to the payment-gateway Confluence space in the last 30 days")
        ok = run.compliance("/audit/verify")
        log = run.brain.audit
        conn = log.conn
        row = conn.execute("SELECT seq, entry_json FROM audit_entries WHERE kind = 'query' ORDER BY seq DESC LIMIT 1").fetchone()
        doc = json.loads(row["entry_json"])
        doc["answer"] = "an edited answer"
        conn.execute("UPDATE audit_entries SET entry_json = ? WHERE seq = ?", (json.dumps(doc, sort_keys=True, separators=(",", ":")), row["seq"]))
        conn.commit()
        broken = log.verify().as_dict()
        conn.execute("UPDATE audit_entries SET entry_json = ? WHERE seq = ?", (row["entry_json"], row["seq"]))
        conn.execute("DELETE FROM audit_entries WHERE seq = ?", (row["seq"] - 1,))
        conn.commit()
        gap = log.verify().as_dict()
        write(
            "scenario-5-audit-inquiry.md",
            "# Scenario 5 — Audit inquiry\n\n" + header
            + "The compliance officer asks: everything jdoe accessed related to the payment-gateway Confluence space in the last 30 days. "
            "The natural-language front maps the question to a schema-validated filter; the canned view groups the indexed decisions by query.\n\n"
            + f"**Derived filter**: `{json.dumps(nl['filter'])}`\n\n"
            + "## Reconstructed trail\n\n"
            + "| Audit # | Time | Query | Document | Gate 1 | Gate 2 | Rule | Version | Refreshed |\n|---|---|---|---|---|---|---|---|---|\n"
            + "\n".join(
                f"| {q['seq']} | {q['ts']} | {q['query']} | `{d['doc']}` | {d['gate1']} | {d['gate2']} | `{d['rule']}` | {d['version']} | {'yes' if d['refreshed'] else ''} |"
                for q in view["queries"] for d in q["decisions"]
            )
            + "\n\nEach row links to the full entry (query, plan, every candidate with its decision, exactly what was sent to the model, the answer, timestamps, hashes). "
            f"The read itself was logged as audit #{view['read_logged_as']}.\n\n"
            + "## Tamper evidence\n\n"
            + f"1. `verify` on the untouched chain: `{json.dumps({k: ok[k] for k in ('ok', 'entries', 'checkpoints_verified')})}`\n"
            + f"2. Edit one answer directly in the database (seq {row['seq']}): `{json.dumps({k: broken[k] for k in ('ok', 'first_broken_seq')})}` — {broken['problems'][0] if broken['problems'] else ''}\n"
            + f"3. Restore it, delete row {row['seq'] - 1}: `{json.dumps({k: gap[k] for k in ('ok', 'gap_after_seq')})}` — {gap['problems'][0] if gap['problems'] else ''}\n\n"
            + "Twenty seconds on stage: `python -m internal_brain.audit.verify --db data/brain.db` before and after `scripts/tamper_demo.py`.\n\n"
            + md_entry(view["queries"][0] if view["queries"] else {}, "First reconstructed query (as returned by the view)"),
        )

        index = [
            "# Scenario walkthroughs",
            "",
            "One worked example per handbook scenario, generated from a real run of the system with the audit entry each produced.",
            "",
            "1. [Unified query](scenario-1-unified-query.md)",
            "2. [Data freshness](scenario-2-freshness.md)",
            "3. [Negative case, no metadata side-channel](scenario-3-negative-case.md)",
            "4. [Live revocation](scenario-4-live-revocation.md)",
            "5. [Audit inquiry](scenario-5-audit-inquiry.md)",
            "",
            "Plus: [Cross-platform stitch](cross-platform-stitch.md) (Drive postmortem to Jira tickets through link expansion).",
            "",
            "Regenerate with `python scripts/run_scenarios.py`. The tests in `tests/test_scenarios.py` assert every beat above.",
            "",
        ]
        write("README.md", "\n".join(index))
    return 0


if __name__ == "__main__":
    sys.exit(main())
